### PR TITLE
Adding Ultra-Lite container

### PR DESCRIPTION
**Pull request by Sam-Burns**
This is a Container-Interop compliant container, implementing the Delegate Lookup feature.

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Any feedback on the container itself would be very gratefully received, btw!

**Comment by drealecs** [comment]
I don't think it implements the delegate lookup feature. For that I think it needs to call the get method on the delegate container with the same service id.

**Comment by Sam-Burns** [comment]
But the [spec](https://github.com/container-interop/container-interop/blob/master/docs/Delegate-lookup-meta.md#41-chosen-approach) says "Calls to the ```get``` method should [...] return an entry if the entry is part of the container".  I thought this meant that if the service exists, it should [return the result](https://github.com/ultra-lite/container/blob/b096a04c970ed177239c287401c9c5301fc2b20d/src/UltraLite/Container/Container.php#L54).  The point is that if the delegate container is set, it should be used in [producing any required dependencies](https://github.com/ultra-lite/container/blob/b096a04c970ed177239c287401c9c5301fc2b20d/tests/phpspec/UltraLiteSpec/UltraLite/Container/ContainerSpec.php#L48-L66) needed in the creation of the requested service.

@mnapoli what's your view on this?

**Comment by drealecs** [comment]
Indeed, maybe I was too fast in responding; I looked a your code and responded from the phone.

I now understood how the ultra-lite container works.
The container is not doing any dependencies lookup himself but is letting the factories to do it.
I don't have anything against the pull request.

**Comment by Sam-Burns** [comment]
Thanks very much for your suggestion.  I will make the docs better :-)

**Comment by mnapoli** [comment]
:+1: after having a look it seems to me that the delegate feature is implemented correctly

**Comment by moufmouf** [comment]
Completely agree. Delegate feature lookup is implemented correctly.

On a side note: Ultra-lite container is looking a lot (some minor differences still) like [Picotainer](https://github.com/thecodingmachine/picotainer) or like [Acclimate's ArrayContainer](https://github.com/jeremeamia/acclimate-container/blob/master/src/ArrayContainer.php).

**Comment by Sam-Burns** [comment]
@moufmouf wow, you've got a point.  I hadn't seen Picotainer before, but they are spookily similar.  I'll update my docs and put a link to it.

Thanks for the feedback guys.

**Pull request merged**
