### PR TITLE
Add auryn-container-interop to Compatible projects

### LINKED ISSUE #75: List Auryn implementation in README?
I'm not sure if or where it makes sense to put this within the sections of the README listing libraries that implement the standard, but I recently created [a library](https://github.com/elazar/auryn-container-interop) that extends [Auryn](https://github.com/rdlowrey/Auryn) in order to add support for the standard to it, as the primary maintainer of Auryn has [expressed disinterest](https://github.com/rdlowrey/Auryn/issues/77#issuecomment-88177594) in adding that support.

### PR DESCRIPTION
**Pull request by elazar**
Fixes #75.

### CODE REVIEW

**Comment by mnapoli** [comment]
Great! I had a look at the implementation and I'm afraid it's not implementing the delegate lookup feature. The point of that feature is that when doing `$container->get('Foo')` the *dependencies* of `Foo` will be fetched from a delegate container (not `Foo` itself).

I'm not sure if it will be possible for you to implement this behavior because Auryn directly calls `$this->make()` when trying to fetch a dependency, for example here: https://github.com/rdlowrey/auryn/blob/master/lib/Injector.php#L455 (instead it should call `$this->delegateContainer->get()`).

**Comment by elazar** [comment]
@mnapoli Odd, I used [xtreamwayz/pimple-container-interop](https://github.com/xtreamwayz/pimple-container-interop/blob/master/src/Container.php) as an example in my implementation, and the two implementations seem fairly similar.

[pimple](https://github.com/xtreamwayz/pimple-container-interop/blob/bb6ba0c9cd050532194ac673a2136dcab203329b/src/Container.php#L27-L78)

[auryn](https://github.com/elazar/auryn-container-interop/blob/1.0.0/src/Container.php#L32-L55)

**Comment by moufmouf** [comment]
Hey @elazar ,

Damn'it :) . The xtreamwayz/pimple-container-interop you are referring to is doing it wrong too....

It is really important to only make a call to the delegate container and not to your container because it is the only way you can delegate the lookup to a "composite container" that contains all the containers in your application. Alas, the delegate lookup feature cannot always be easily done by extending a container (you have to change the inner workings of the container which is not always possible).

If you want to have a look at a correct (and very minimalistic implementation), you can check Picotainer:

https://github.com/thecodingmachine/picotainer/blob/1.0/src/Picotainer.php

**Comment by pyrsmk** [comment]
Hum... Is that mean that you must not have several delegate containers in one container?

**Comment by moufmouf** [comment]
@pyrsmk  Yes absolutely, there can be only one.

**Comment by pyrsmk** [comment]
So is delegating only useful with a "composite container"? I never encountered a case where I could need it, so I hardly see the use case of it.

**Comment by moufmouf** [comment]
Exactly. This feature is really designed to help with composite containers (and I believe nothing more). Composite containers is the only sane way to have several containers working side by side (with each container being able to access the entries of its fellow containers)

**Comment by pyrsmk** [comment]
Ok, I better see how it's working... Have you got an example of a simple implementation of a composite container?

**Comment by moufmouf** [comment]
Sure! There is one in Acclimate: https://github.com/jeremeamia/acclimate-container/blob/master/src/CompositeContainer.php

**Comment by mnapoli** [comment]
If you meant "an example of a container implementing the delegate lookup feature" here is one: https://github.com/ultra-lite/container/blob/master/src/UltraLite/Container/Container.php#L65

**Comment by mnapoli** [comment]
(and by looking at implementations references in the README I realized many don't actually implement that feature correctly)

**Comment by pyrsmk** [comment]
@moufmouf : great, that's how I was seeing this ^^ I think I'll implement this in Chernozem like Picotainer

**Comment by elazar** [comment]
@mnapoli I've updated this PR to reflect that auryn-container-interop supports `ContainerInterface`, but not the delegate lookup feature. Feel free to merge at your convenience. Thanks to you and @moufmouf for your guidance in this discussion.

**Comment by mnapoli** [comment]
:+1:

**Pull request merged**
