### PR TITLE
Migrating container-interop to PSR-11

### LINKED ISSUE #90: Implement PSR-11?
Hi everyone :)

For those not following the latest events, PSR-11 has gone into vote and it's going quite well. If it passes, what should we do (and what can we do)?

Is there any technical reason not to implement PSR-11?

Should we deprecate container-interop?

My opinion for what it's worth:

- if there is nothing preventing that, this package should extend PSR-11 (for an easy migration)
- it could be deprecated, but we shouldn't forget about the dependency lookup feature (which is not included in PSR-11)

### PR DESCRIPTION
**Pull request by moufmouf**
Following discussion at #90, this PR implements PSR-11 and adds a deprecation warning at the forefront of the README.

Closes #90 

Feedback needed. **Not to be merged before Feb 13th!**

### CODE REVIEW

**Comment by mnapoli** [comment]
Looks good to me but I guess it would be better to try it out before merging just to be sure? I'll give it a try with PHP-DI

**Review by Ocramius — APPROVED** [review]

**Comment by Sam-Burns** [comment]
Looks ok for Slim framework.  I've created a [PR](https://github.com/slimphp/Slim/pull/2146) converting the application's container to a PSR-11 container.  It also allows users to swap in another PSR-11 container.

It requires `"container-interop/container-interop": "^2.0"`, so it is caught by Composer if a user is trying to swap in a container which only implements `container-interop/container-interop` version 1.

Exceptions implement `Interop\Container\Exception\ContainerException` _and_ `Psr\Container\ContainerExceptionInterface`, so user-land code can still catch them as Container-Interop exceptions.

It seems to me that the upgrade path works ok 👍

**Comment by mnapoli** [comment]
@Sam-Burns why do we need to tag a new major version? (2.0) If we keep BC then this can be a 1.2 and all containers (implementors) would be automatically compatible with PSR-11 without needing any new release right?

**Comment by Sam-Burns** [comment]
@mnapoli Sure, that sounds fine.

**Review by weierophinney — APPROVED** [review]
Agreed with @mnapoli — this is completely BC at this point; a new minor version will allow folks to upgrade, while adding compatibility with psr/container.

I tagged psr/container 1.0.0 just a few minutes ago, which means that this can be merged and tagged any time now.

**Comment by jeremeamia** [comment]
Congrats container-interop, you've stood the test of time.

**Comment by moufmouf** [comment]
@mnapoli Any additional checks you want to perform? Can I merge this?

**Comment by mnapoli** [comment]
All good!

**Pull request merged**
